version: '3'

services:
  
  app-node: 
    image: mi-node
    build: ./
    container_name: app-node
    working_dir: /app
    volumes:
      - "./index.js:/app/index.js"
    depends_on:
      - db

  db:
    image: mongo:4
    container_name: mi-mongo
    volumes:
      - dbvol:/data/db

volumes:
  dbvol:

